### ISSUE TITLE
LDA models are missing. LocalLDAModel and DistributedLDAModel

### ISSUE THREAD

**Issue by tylerfordML** [Hydrospheredata/spark-ml-serving#24]
I am trying to use an lda algorithm and it cant find it in this lib. can you give me an example of how to add something like this ?

**Comment by KineticCookie** [comment]
Hello @tylerfordML 

> I am trying to use an lda algorithm and it cant find it in this lib

LDA is not implemented yet.

> can you give me an example of how to add something like this ?

Sure,  take a look at KMeansModel [implementation](https://github.com/Hydrospheredata/spark-ml-serving/blob/master/src/main/scala/io/hydrosphere/spark_ml_serving/clustering/LocalKMeansModel.scala) 

Implementation of context-less KMeansModel can be separated into 2 parts:

1. We need to re-implement the transformation of the model, so it doesn't need SparkContext

2. And the model needs to be loaded from parquet without SparkContext.

To implement a context-less KMeansModel, we must create a wrapper class and extend `LocalTransformer[KMeansModel]` trait. 
But before implementing `LocalTransformer.transform`, we must analyze `KMeansModel.transform`.

	```
	class KMeansModel private[ml] (
    override val uid: String,
    private val parentModel: MLlibKMeansModel)
  	extends Model[KMeansModel] with KMeansParams with MLWritable {
	  override def transform(dataset: Dataset[_]): DataFrame = {
	    transformSchema(dataset.schema, logging = true)
	    val predictUDF = udf((vector: Vector) => predict(vector))
	    dataset.withColumn($(predictionCol), predictUDF(col($(featuresCol))))
	  }
	  private[clustering] def predict(features: Vector): Int = parentModel.predict(features)
	  // ...
	 }
	```
As you can see to remove SparkContext from implementation, we must get rid of `Dataset[_]`. 
We can narrow down the implementation of algorithm to `predict` method, which calls `MLlibKMeansModel.predict`. Since `Vector` doesn't need a SparkContext, we can now set up a context-less implementation.

In conclusion, `LocalTransformer.transform` will:
	1. get `parentModel` field from wrapped `KMeansModel`
	2. get `KMeansModel` input/output fields
	3. call `parentModel.predict` on our input values. (Note that we must return non-Spark types in output fields. If there is a Vector as a return type please convert it to List)

To load the model without SparkContext, we implement a companion object, which extends `SimpleModelLoader[KMeansModel]`. 
Implementation of `SimpleModelLoader.build` also requires an analysis of how model stored and constructed. You need to extract constructor parameters and model parameters from method arguments and create a `KMeansModel` object.

The last but not the least, you need to define compile-time and run-time conversions `KMeansModel` -> `LocalKMeansModel`. 
Implementing a `TypedTransformerConverter[KMeansModel]` trait in companion object defines a compile-time conversion.
Extending the matches in `CommonLoaderConversions` and `CommonTransormerConversions` helps with run-time conversions.

That's all the implementation details. Next, we need to write tests for `KMeansModel` for each Spark version to ensure that expected behavior is consistent. 
If we see the inconsistency between versions, we split it, and re-implement the algorithm depending on version features.

In case of LDA, you need to implement traits mentioned above for both `LocalLDAModel` and `DistributedLDAModel`.
